<?php

namespace app\modules\api\controllers;
use app\models\Check;
use app\models\Dish;
use app\modules\api\services\CheckService;
use yii\db\Exception;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\Controller;
use yii\web\Response;

/**
 * Book controller for the `api` module
 */
class CheckController extends Controller
{
    /**
     * @return array|array[]
     */
    public function behaviors(): array
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['contentNegotiator']['formats'] = ['application/json' => Response::FORMAT_JSON];
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::className(),
        ];
        return $behaviors;
    }

    public function verbs(): array
    {
        return [
            'POST' => 'open'
        ];
    }

    /**
     * @return int|null
     */
    public function actionOpen()
    {
        try {
            return CheckService::openCheck();
        } catch (Exception $e) {
            $this->response->statusCode = $e->getCode();
            return null;
        }
    }

    /**
     * @param int $dishId
     * @param $checkId
     * @return void
     */
    public function actionAttachDish(int $dishId, $checkId)
    {
        try {
            $check = Check::findOne($checkId);
            $dish = Dish::findOne($dishId);
            $check->link('dishes', $dish);
            $this->response->statusCode = 201;
        } catch (\Exception $e) {
            $this->response->statusCode = $e->getCode();
            $this->response->data = ['message' => $e->getMessage()];
        }
    }
}
