<?php

namespace app\modules\api\controllers;
use app\modules\api\forms\CookApiSearch;
use app\modules\api\forms\DishApiSearch;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\Controller;
use yii\web\Response;

/**
 * Cook controller for the `api` module
 */
class CookController extends Controller
{
    /**
     * @return array|array[]
     */
    public function behaviors(): array
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['contentNegotiator']['formats'] = ['application/json' => Response::FORMAT_JSON];
        $behaviors['authenticator'] = [
            'class' => HttpBasicAuth::className(),
        ];
        return $behaviors;
    }

    public function verbs(): array
    {
        return [
            'GET' => 'index'
        ];
    }

    /**
     * @return \yii\data\ActiveDataProvider
     */
    public function actionIndex()
    {
        $searchModel = new CookApiSearch();
        $data = $searchModel->search(\Yii::$app->request->queryParams);
        $this->response->statusCode = 200;
        return $data;
    }
}
